export const TAMIL = {
    "OKAY": "சரி",
    "RESET": "மீட்டமை",
    "Faults": "தவறுகள்",
    "Machine Code": "இயந்திர எண்",
    "Parts": "பாகங்கள்",
    "Qty": "அளவு",
    "SUBMIT": "நுழைய",
    "Enter Parts to give ESTIMATE": "Matippīṭṭaik koṭukka pakutikaḷai uḷḷiṭavum",
    "Estimate NOT APPROVED by customer": "வாடிக்கையாளரால் அங்கீகரிக்கப்படாத மதிப்பீடு",
    "Please enter a MachineCode": "Iyantira eṇṇai uḷḷiṭavum",
    "FULL CHECK": "முழு சரிபார்ப்பு",
    "WIRECORD": "கம்பி பதிவு",
    "T/HANDLE": "டி/கைப்பிடி",
    "B/HANDLE": "பி/கைப்பிடி",
    "R/G BULB": "ஆர்/ஜி பல்பு",
    "LAMPBOX": "விளக்குப்பெட்டி",
    "LAMPBOX SET": "LampBox Set",
    "SHOCK": "அதிர்ச்சி",
    "CHECK HEAT": "வெப்பத்தை சரிபார்க்கவும்",
    "BROKEN PLATE": "உடைந்த தட்டு",
    "RIVIT": "ரிவிட்",
    "CHECK ALIGNMENT": "சீரமைப்பைச் சரிபார்க்கவும்",
    "T/COATING": "டி/பூச்சு",
    "B/COATING": "பி/பூச்சு",
    "THERMOSTAT": "தெர்மோஸ்டாட்",
    "REVIT": "ரிவிட்",
    "F.G WIRE SET": "எஃப்.ஜி வயர் செட்",
    "HANDLE": "கைப்பிடி",
    "ELEMENT": "உறுப்பு",
    "LAMP BOX": "விளக்குப்பெட்டி",
    "COATING": "பூச்சு",
    "NEW PLATE": "புதிய தட்டு",
    "NEW KHUMSA": "புதிய கும்சா",
    "3 PIN": "3 பின்",
    "BASE REPAIR CHARGE": "BASE REPAIR CHARGE",
    "CONFIRM": "உறுதி",
    "CANCEL": "ரத்து செய்",
    "Are you sure you want to submit parts?": "பாகங்களைச் சமர்ப்பிக்க விரும்புகிறீர்களா?",
    "ESTIMATE has been submitted": "மதிப்பீடு சமர்ப்பிக்கப்பட்டது",
    "Parts have been submitted": "பாகங்கள் சமர்ப்பிக்கப்பட்டுள்ளன",
    "Please enter values before submitting":"Camarppikkum muṉ matippukaḷai uḷḷiṭavum",
    "Please select a part before submitting":"சமர்ப்பிக்கும் முன் ஒரு பகுதியைத் தேர்ந்தெடுக்கவும்"
};